bootstrap_servers: 'localhost:9092'
topic: quickstart-events
security_protocol: SSL
#  ssl_truststore_location: /path/to/truststore.jks
#  ssl_truststore_password: truststore_password
#  ssl_keystore_location: /path/to/keystore.jks
#  ssl_keystore_password: keystore_password
auto_offset_reset: earliest # latest
group_id: test-consumer-group
client_id: kafka_consumer_client
auto_commit: true
auto_commit_interval_ms: 1000
heartbeat_interval_ms: 3000
session_timeout_ms: 30000
request_timeout_ms: 40000
fetch_min_bytes: 1
fetch_max_bytes: 52428800
max_partition_fetch_bytes: 10485760
max_poll_records: 1000
key_deserializer: org.apache.kafka.common.serialization.StringDeserializer
value_deserializer: org.apache.kafka.common.serialization.StringDeserializer
